project:
  type: website
  output-dir: docs
  preview:
    port: 8080
  render:
    - README.md
    - "slides/*"
    - "1. yandex_kube.md"
    - "2. clearml_yandex_kube.md"
    - "2.2 clearml docker.md"
    - "3. clearml_work.md"
    - "4. clearml_data.md"
    - "5. clearml_pipeline.md"
    - "6. clearml_research.md"
    - "7. clearml_reports.md"
    - "8. clearml_serving.md"
    - "9. clearml_extend_pipes.md"

website:
  title: "MLOps/DataOps YA.Camp 2025"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: Лекции
      contents: slides/*
    - section: Практика
      contents:
      - 1. yandex_kube.md
      - 2. clearml_yandex_kube.md
      - 2.2 clearml docker.md
      - 3. clearml_work.md
      - 4. clearml_data.md
      - 5. clearml_pipeline.md
      - 6. clearml_research.md
      - 7. clearml_reports.md
      - 8. clearml_serving.md
      - 9. clearml_extend_pipes.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true