
auth {
    # Fixed users login credentials
    # No other user will be able to login
    fixed_users {
        enabled: true
        pass_hashed: false
        users: [
            {
                username: "levkovalenko"
                password: "12345678"
                name: "Лев Коваленко"
            },
        ]
    }
}

apiserver {
    files {
        default_storage {
            fileserver: "http://fileserver:8081"
            base_url: "http://fileserver:8081"
        }
    }
}